### ISSUE TITLE
[Feature request]: Sort packages

### ISSUE THREAD

**Issue by VisenDev** [Zigistry/Zigistry#38]
It would be nice if you could sort the results based on
- Star count
- Last update
- Forks
- Etc...

**Comment by RohanVashisht1234** [comment]
Thanks a lot for opening this issue, I have implemented sorting algorithm to both Zigistry's packages and programs search results.

Check it out: https://zigistry.dev/

https://github.com/user-attachments/assets/70226049-dfc4-420e-b197-37d534ec4373

![image](https://github.com/user-attachments/assets/cc18f113-eacd-446f-b503-b45fa7de04d9)
