### ISSUE TITLE
[BUG]: Display markdown checkboxes

### ISSUE THREAD

**Issue by tealsnow** [Zigistry/Zigistry#39]
**Describe the bug**
The `- [ ]` / `- [x]` checkbox syntax extension for Markdown is not displayed; where it is on GitHub.

**To Reproduce**
1. In the repo https://github.com/basdp/skia-zig ; zigistry url: https://zigistry.dev/packages/basdp/skia-zig
2. And look under the 'Project status' heading

**Expected behavior**
Checkboxes to be rendered respective of their checked or unchecked state

**Screenshots**
On *GitHub* the checkboxes are shown:
![zigistry md checkbox github](https://github.com/user-attachments/assets/f2a25a5e-dcba-41dc-aa38-6e666867d458)

But on *Zigistry* the checkboxes are absent:
![zigistry md checkbox bug](https://github.com/user-attachments/assets/54b6a33c-dcbd-4d7a-bf8b-f66d5fb7da2e)

**Desktop (please complete the following information):**

- Device: laptop
- Screen: 1366x768
- Browser zen-browser (firefox)
- Version Mozilla Zen 1.0.1-a.22

**Smartphone (please complete the following information):**

`N/A`

**Additional context**

*btw just found out about this project. Excited about its future. Keep up the good work! :smile:

**Comment by tealsnow** [comment]
That is strange. Just tested it with chrome, same issue.

And looking at the inspected HTML:
```html
<ul>
<li> Skia build for Windows x86_64</li>
<li> Skia build for macOS x86_64</li>
<li> Skia build for macOS Apple Silicon</li>
<li> Skia build for Linux</li>
</ul>
```
There doesn't seem to be anything for the checkboxes.

I'm not too familiar with website deployment in general, but could this be a CDN or some other caching / versioning issue? i.e. I'm not getting the latest version of the website?

**Comment by RohanVashisht1234** [comment]
No, the screenshot which I sent you is on my machine

**Comment by RohanVashisht1234** [comment]
I am asking if the changes I made look fine.

**Comment by RohanVashisht1234** [comment]
Thanks a lot for opening this issue, I have fixed and pushed the changes, check it out:  https://zigistry.dev/packages/basdp/skia-zig

The checkbox is now correctly visible.

![](https://i.imgflip.com/9cdghb.jpg)

**Comment by tealsnow** [comment]
Ah. Totally misunderstood you. My head was not in the space of considering styles. It's not my forte.
Thanks for the fix :+1:
