### ISSUE TITLE
[BUG]: New Zig game, not getting picked up by Zigistry: https://github.com/deckarep/freegemas

### ISSUE THREAD

**Issue by deckarep** [Zigistry/Zigistry#42]
Hi, my new Zig-based SDL2 game is not getting picked up even though it's been tagged with Zig for a few days now.
https://github.com/deckarep/freegemas

**Expected behavior**
The game searchable from Zigistry

**Additional context**
Love Zigistry and it's filling a much needed gap in the community for package discovery!

**Comment by RohanVashisht1234** [comment]
It has already been added to zigistry programs.
https://zigistry.dev/programs/deckarep/freegemas

**Comment by deckarep** [comment]
Oh thank you. I failed to realize that there was a separate search for programs.

Maybe it would be useful to provide a global search at the top, otherwise people would have to know what is a package vs program.

Thanks for clearing things up for me! It’s very appreciated!
